<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="2" time="0.012" timestamp="2025-09-28T09:02:19.797041-04:00" hostname="0587456217.wireless.umich.net"><testcase classname="testing_chat.test_stats" name="test_median_odd_count" time="0.000" /><testcase classname="testing_chat.test_stats" name="test_median_even_count_simple" time="0.000"><failure message="assert 3 == 2.5&#10; +  where 3 = median([1, 3, 2, 4])">def test_median_even_count_simple():
        # Correct median is average of middle two after sorting.
&gt;       assert median([1, 3, 2, 4]) == 2.5
E       assert 3 == 2.5
E        +  where 3 = median([1, 3, 2, 4])

testing_chat/test_stats.py:14: AssertionError</failure></testcase></testsuite></testsuites>